### ISSUE TITLE
setup install issues w Win10

### ISSUE THREAD

**Issue by tony-shannon** [frectal/React2JSONDB_starterK1#5]
@Ddzhenyik could you please add some notes here about troubleshooting the install on Win 10K machine, webpack, win cmd v Atom etc
thanks
T

**Comment by tony-shannon** [comment]
As I've tried to set up a second instance on my Win10 machine , following the install instructions and its failed again

**Comment by Ddzhenyik** [comment]
@tony-shannon sure!
At first for running commands on Win10 machine it's better to user default terminal "cmd" instead of built in editors like Atom, PHPStorm etc.. In case of installation process goes bad it may need to run cmd with admin rights. 
And one more thing regarding "npm run start" command. If some of the modules couldn't be resolved during running application, it's more likely  because of "npm install" process wasn't finished successfully. To fix this issue it needs to remove "node_modules" folder, remove webpack-dev-server using command "npm uninstall -g webpack-dev-server", and then re-run installation.

**Comment by tony-shannon** [comment]
many thanks, using the Win10 "cmd" terminal as administrator (right click on the icon to access this) and following the install instructions, seemed to work for me thanks
